# Data Inconsistencies

## 1.Inconsistent Formats

In [53]:
# import libraries for ml tasks 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [54]:
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['Arsal', 'Ahmed', 'Abdullah', 'Arsal'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}
# make pandas dataframe
df = pd.DataFrame(data)
df

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA     Arsal       100.0         NaN
1  01-12-2022         U.S.A.     Ahmed       200.0       150.0
2  2022/12/01        America  Abdullah         NaN       300.0
3  12-01-2021  United States     Arsal       200.0       150.0

### 1.Convert to Datetime: 
Use pd.to_datetime with errors='coerce' to convert the column. This will set invalid dates to NaT.

In [55]:
# standardizing the date column 
df['date']=pd.to_datetime(df['date'],errors='coerce')
df['date']=df['date'].dt.strftime('%y-%m-%d')
df

       date        country      name  sales_2020  sales_2021
0  21-12-01            USA     Arsal       100.0         NaN
1       NaN         U.S.A.     Ahmed       200.0       150.0
2       NaN        America  Abdullah         NaN       300.0
3       NaN  United States     Arsal       200.0       150.0

### 2.Fill Missing Values: 
Use methods like fillna() to impute missing values. You can fill with a specific date, the mean date, or forward/backward fill.

In [56]:
# Step 1: Convert to datetime, coercing errors
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Step 2: Check for NaT values
print("Before filling NaT values:")
print(df)

# Step 3: Impute or fill missing values
# Example: Fill NaT with a specific date (e.g., '2021-01-01')
df['date'].fillna(pd.Timestamp('2001-12-21'), inplace=True)

# Alternatively, use forward fill
# df['date'].fillna(method='ffill', inplace=True)

# Print the DataFrame after imputation
print("\nAfter filling NaT values:")
print(df)

Before filling NaT values:
        date        country      name  sales_2020  sales_2021
0 2001-12-21            USA     Arsal       100.0         NaN
1        NaT         U.S.A.     Ahmed       200.0       150.0
2        NaT        America  Abdullah         NaN       300.0
3        NaT  United States     Arsal       200.0       150.0

After filling NaT values:
        date        country      name  sales_2020  sales_2021
0 2001-12-21            USA     Arsal       100.0         NaN
1 2001-12-21         U.S.A.     Ahmed       200.0       150.0
2 2001-12-21        America  Abdullah         NaN       300.0
3 2001-12-21  United States     Arsal       200.0       150.0

> Interpretation:
1. The pd.to_datetime function converts the date column, coercing invalid entries to NaT.
2. You can inspect the DataFrame to see which values are NaT.
3. Use fillna() to replace NaT values. You can choose to fill with a specific date, or apply methods like forward fill (ffill) or backward fill (bfill) based on your needs.


This approach ensures that your date column is consistent and ready for further analysis.

## 2.Naming Convention

In [57]:
df.head()

        date        country      name  sales_2020  sales_2021
0 2001-12-21            USA     Arsal       100.0         NaN
1 2001-12-21         U.S.A.     Ahmed       200.0       150.0
2 2001-12-21        America  Abdullah         NaN       300.0
3 2001-12-21  United States     Arsal       200.0       150.0

In [58]:
# Harmonize the Name of Country 
mapping = {'USA': 'United States', 'U.S.A.': 'United States', 'America': 'United States'}
df['country'] = df['country'].replace(mapping)
df

        date        country      name  sales_2020  sales_2021
0 2001-12-21  United States     Arsal       100.0         NaN
1 2001-12-21  United States     Ahmed       200.0       150.0
2 2001-12-21  United States  Abdullah         NaN       300.0
3 2001-12-21  United States     Arsal       200.0       150.0

## 3.Typographical Inconsistency

In [59]:
# correct the typographical inconsistency in the name column
df['name']=df['name'].replace({'Arsal':'Arsalan'})
df

        date        country      name  sales_2020  sales_2021
0 2001-12-21  United States   Arsalan       100.0         NaN
1 2001-12-21  United States     Ahmed       200.0       150.0
2 2001-12-21  United States  Abdullah         NaN       300.0
3 2001-12-21  United States   Arsalan       200.0       150.0

## 4.Remove Duplicates

In [44]:
df.drop_duplicates(subset='name',inplace=True)
df

        date        country      name  sales_2020  sales_2021
0 2001-12-21  United States   Arsalan       100.0         NaN
1 2001-12-21  United States     Ahmed       200.0       150.0
2 2001-12-21  United States  Abdullah         NaN       300.0

## 5.Contradictory Inconsistency

In [62]:
df = df.drop(df[df['sales_2021']<=df['sales_2020']].index)
df

        date        country      name  sales_2020  sales_2021
0 2001-12-21  United States   Arsalan       100.0         NaN
2 2001-12-21  United States  Abdullah         NaN       300.0