# Handling Outliers

In [10]:
import pandas as pd
import numpy as np
#  1.create a dataframe
df = pd.DataFrame({'Age':[7,8,9,10,11,12,13,14,34,50]})
# 2.find mean and standard deviation
mean = np.mean(df['Age'])
std = np.std(df['Age'])
# 3.find the z-scores
df['Z-Score'] = (df['Age']-mean)/std
df

   Age   Z-Score
0    7 -0.739207
1    8 -0.663778
2    9 -0.588348
3   10 -0.512919
4   11 -0.437490
5   12 -0.362061
6   13 -0.286631
7   14 -0.211202
8   34  1.297384
9   50  2.504252

In [11]:
outliers = df[np.abs(df['Z-Score']) > 3]
outliers

Empty DataFrame
Columns: [Age, Z-Score]
Index: []

In [12]:

# print the outliers
df[np.abs(df['Z-Score']>3)]

Empty DataFrame
Columns: [Age, Z-Score]
Index: []

In [13]:
# print the clean data 
df[np.abs(df['Z-Score']<3)]

   Age   Z-Score
0    7 -0.739207
1    8 -0.663778
2    9 -0.588348
3   10 -0.512919
4   11 -0.437490
5   12 -0.362061
6   13 -0.286631
7   14 -0.211202
8   34  1.297384
9   50  2.504252

# Scipy Method

In [28]:
from scipy import stats
import pandas as pd
import numpy as np
#  1.create a dataframe
df = pd.DataFrame({'Age':[7,8,9,10,11,12,13,14,34,50]})
df['Z-Score'] = np.abs(stats.zscore(df['Age']))
thresold = 2.5
df[np.abs(df['Z-Score'] >= thresold)]

   Age   Z-Score
9   50  2.504252

In [29]:
df[np.abs(df['Z-Score'] < thresold)]

   Age   Z-Score
0    7  0.739207
1    8  0.663778
2    9  0.588348
3   10  0.512919
4   11  0.437490
5   12  0.362061
6   13  0.286631
7   14  0.211202
8   34  1.297384

In [41]:
from sklearn.cluster import KMeans
data = [[2,2],[3,3],[3,4],[30,30],[31,32],[32,32]]
model = KMeans(n_clusters=2,n_init=10)
model.fit(data)
labels = model.predict(data)
outlier = [data[i] for i,label in enumerate(labels) if label==1]
print(f"Data : {data}")
print(f"outlier : {outlier}")
data_clean = [data[i] for i , label in enumerate(labels) if label ==0]
print(f"Clean Data : {data_clean}")

Data : [[2, 2], [3, 3], [3, 4], [30, 30], [31, 32], [32, 32]]
outlier : [[30, 30], [31, 32], [32, 32]]
Clean Data : [[2, 2], [3, 3], [3, 4]]