# Random Forest Model

Random forests can handle missing values inherently. They can also be used to predict missing values based on the patterns learned from the other data.

Let's see how to implement random forests in Python using the Titanic dataset.

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.impute import SimpleImputer

df = sns.load_dataset('titanic')

df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [4]:
df.drop('deck',axis=1,inplace=True)

df.isnull().sum().sort_values(ascending=False)

age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
parch            0
sibsp            0
class            0
fare             0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

# Encoding Categorical Variables

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Define the columns to encode as a list
columns_to_encode = ['sex','embarked','who','class','embark_town','alive']
# Create a LabelEncoder dictionary to store the encoders for each column
label_encoder = {}
# Loop through the columns to encode
for col in columns_to_encode:
    # Create a LabelEncoder object for the each column
    le = LabelEncoder()
    # Fit and transform the column using the LabelEncoder
    df[col] = le.fit_transform(df[col])
    # Store the LabelEncoder object so we can use it later
    label_encoder[col] = le

df.head()

   survived  pclass  sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    1  22.0  ...        True            2      0  False
1         1       1    0  38.0  ...       False            0      1  False
2         1       3    0  26.0  ...       False            2      1   True
3         1       1    0  35.0  ...       False            2      1  False
4         0       3    1  35.0  ...        True            2      0   True

[5 rows x 14 columns]

In [ ]:
# Create separate DataFrames for missing and non-missing values
df_with_missing = df[df['age'].isna()]
df_without_missing = df.dropna()

In [7]:
print("The shape of the original dataset is: ", df.shape)
print("The shape of the dataset with missing values removed is: ", df_without_missing.shape)
print("The shape of the dataset with missing values is: ", df_with_missing.shape)

The shape of the original dataset is:  (891, 14)
The shape of the dataset with missing values removed is:  (714, 14)
The shape of the dataset with missing values is:  (177, 14)

In [9]:
# Display the first few rows of the dataset with missing values
df_with_missing.head()

    survived  pclass  sex  age  ...  adult_male  embark_town  alive  alone
5          0       3    1  NaN  ...        True            1      0   True
17         1       2    1  NaN  ...        True            2      1   True
19         1       3    0  NaN  ...       False            0      1   True
26         0       3    1  NaN  ...        True            0      0   True
28         1       3    0  NaN  ...       False            1      1   True

[5 rows x 14 columns]

In [10]:
# Display the first few rows of the dataset without missing values
df_without_missing.head()

   survived  pclass  sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    1  22.0  ...        True            2      0  False
1         1       1    0  38.0  ...       False            0      1  False
2         1       3    0  26.0  ...       False            2      1   True
3         1       1    0  35.0  ...       False            2      1  False
4         0       3    1  35.0  ...        True            2      0   True

[5 rows x 14 columns]

In [11]:
# check the names of the columns 
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

# Train Model

In [ ]:
# Create feature and target datasets
X = df_without_missing.drop('age', axis=1)
y = df_without_missing['age']

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create an instance of the RandomForestRegressor class
model = RandomForestRegressor(n_estimators=40, random_state=42)

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model's performance
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")
print(f"Root Mean Squared Error: {np.sqrt(mean_squared_error(y_test, y_pred))}")
print(f"R-squared: {r2_score(y_test, y_pred)}")

Mean Absolute Error: 8.28305672309371
Mean Squared Error: 117.64832948514045
Root Mean Squared Error: 10.846581465380714
R-squared: 0.3613362471737668

In [ ]:
# Check for remaining missing values
df_with_missing.isnull().sum().sort_values(ascending=False)

age            177
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

# Make Prediction

In [23]:
# predict the missing values in the 'age' column
y_pred = model.predict(df_with_missing.drop('age', axis=1))
# Fill the missing values with the predicted values
df_with_missing['age'] = y_pred
# Check for remaining missing values
df_with_missing.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [34]:
# concatenate the two DataFrames 
df_complete = pd.concat([df_without_missing,df_with_missing],axis=0)

# print the shape of the new DataFrame
print("The shape of the dataset with missing values is: ", df_complete.shape)
print("The shape of the dataset without missing values is: ", df_without_missing.shape)
print("The shape of the dataset with missing values is: ", df_with_missing.shape)

The shape of the dataset with missing values is:  (891, 14)
The shape of the dataset without missing values is:  (714, 14)
The shape of the dataset with missing values is:  (177, 14)

# Decoding Categorical Variables

In [35]:
# Decoding Categorical Variables
for col in columns_to_encode:
    # Retrieve the LabelEncoder for each column
    le = label_encoder[col]
    # Apply the inverse transform to the column in df_complete
    df_complete[col] = le.inverse_transform(df_complete[col])

df_complete.head(14)

    survived  pclass     sex   age  ...  adult_male  embark_town  alive  alone
0          0       3    male  22.0  ...        True  Southampton     no  False
1          1       1  female  38.0  ...       False    Cherbourg    yes  False
2          1       3  female  26.0  ...       False  Southampton    yes   True
3          1       1  female  35.0  ...       False  Southampton    yes  False
4          0       3    male  35.0  ...        True  Southampton     no   True
6          0       1    male  54.0  ...        True  Southampton     no   True
7          0       3    male   2.0  ...       False  Southampton     no  False
8          1       3  female  27.0  ...       False  Southampton    yes  False
9          1       2  female  14.0  ...       False    Cherbourg    yes  False
10         1       3  female   4.0  ...       False  Southampton    yes  False
11         1       1  female  58.0  ...       False  Southampton    yes   True
12         0       3    male  20.0  ...        True  Southampton     no   True
13         0       3    male  39.0  ...        True  Southampton     no  False
14         0       3  female  14.0  ...       False  Southampton     no   True

[14 rows x 14 columns]

In [38]:
# print the shape of imputed DataFrame
print("The shape of the imputed dataset is: ", df_complete.shape)

The shape of the imputed dataset is:  (891, 14)

In [37]:
# check the missing values after imputation
df_complete.isnull().sum().sort_values(ascending=False)

embark_town    2
embarked       2
sex            0
age            0
survived       0
pclass         0
parch          0
sibsp          0
class          0
fare           0
who            0
adult_male     0
alive          0
alone          0
dtype: int64