# **Inverse encoding/ Inverse transform /Decoding categorical variables**

Inverse encoding is the process of converting the encoded data back to its original form. This is done by using the **inverse_transform()** method. This method is available for the following encoders:

- LabelEncoder
- OrdinalEncoder
- OneHotEncoder

In [2]:
# import libraries
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
# load the dataset
df = sns.load_dataset('titanic')
# display the first few rows of the dataset
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [18]:
# impute missing values 
df['age'].fillna(df['age'].mean(), inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0], inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

# drop columns that are not needed
df.drop('deck',axis=1,inplace=True)

# Label Encoder

In [19]:
# encode all the object & categorical variables 
le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_embark_town = LabelEncoder()
le_who = LabelEncoder()
le_alive = LabelEncoder()
le_alone = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['who'] = le_who.fit_transform(df['who'])
df['alive'] = le_alive.fit_transform(df['alive'])
df['alone'] = le_alone.fit_transform(df['alone'])

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,Third,1,True,2,0,0
1,1,1,0,38.0,1,0,71.2833,0,First,2,False,0,1,0
2,1,3,0,26.0,0,0,7.9250,2,Third,2,False,2,1,1
3,1,1,0,35.0,1,0,53.1000,2,First,2,False,2,1,0
4,0,3,1,35.0,0,0,8.0500,2,Third,1,True,2,0,1

In [ ]:
# Apply Inverse Transform to decode the encoded variables
df['sex'] = le_sex.inverse_transform(df['sex'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,2,Third,1,True,2,0,0
1,1,1,female,38.0,1,0,71.2833,0,First,2,False,0,1,0
2,1,3,female,26.0,0,0,7.9250,2,Third,2,False,2,1,1
3,1,1,female,35.0,1,0,53.1000,2,First,2,False,2,1,0
4,0,3,male,35.0,0,0,8.0500,2,Third,1,True,2,0,1

# OHE

In [22]:
ohe_sex = OneHotEncoder(sparse_output=False)
ohe_embarked = OneHotEncoder(sparse_output=False)
ohe_embark_town = OneHotEncoder(sparse_output=False)
ohe_who = OneHotEncoder(sparse_output=False)
ohe_alive = OneHotEncoder(sparse_output=False)
ohe_alone = OneHotEncoder(sparse_output=False)

# One-hot encode the categorical variables
df['sex'] = ohe_sex.fit_transform(df[['sex']])
df['embarked'] = ohe_embarked.fit_transform(df[['embarked']])
df['embark_town'] = ohe_embark_town.fit_transform(df[['embark_town']])
df['who'] = ohe_who.fit_transform(df[['who']])
df['alive'] = ohe_alive.fit_transform(df[['alive']])
df['alone'] = ohe_alone.fit_transform(df[['alone']])

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,0.0,22.0,1,0,7.2500,0.0,Third,0.0,True,0.0,1.0,1.0
1,1,1,1.0,38.0,1,0,71.2833,1.0,First,0.0,False,1.0,0.0,1.0
2,1,3,1.0,26.0,0,0,7.9250,0.0,Third,0.0,False,0.0,0.0,0.0
3,1,1,1.0,35.0,1,0,53.1000,0.0,First,0.0,False,0.0,0.0,1.0
4,0,3,0.0,35.0,0,0,8.0500,0.0,Third,0.0,True,0.0,1.0,0.0

In [29]:
from sklearn.preprocessing import OneHotEncoder
df = sns.load_dataset('titanic')

cat_columns = ['sex','who']
encoder = OneHotEncoder(sparse_output=False)
encoded_df = pd.DataFrame(encoder.fit_transform(df[cat_columns]))
df = pd.concat([df,encoded_df],axis=1)
df.drop(cat_columns,axis=1,inplace=True)
df.head()

,survived,pclass,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone,0,1,2,3,4
0,0,3,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False,0.0,1.0,0.0,1.0,0.0
1,1,1,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False,1.0,0.0,0.0,0.0,1.0
2,1,3,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0
3,1,1,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False,1.0,0.0,0.0,0.0,1.0
4,0,3,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True,0.0,1.0,0.0,1.0,0.0

In [27]:
# encoded_df = pd.DataFrame(encoder.inverse_transform(encoded_df))
encoded_df.head()

        0      1
0    male    man
1  female  woman
2  female  woman
3  female  woman
4    male    man

In [30]:
# We need to extract the original categories for each encoded column
original_categories = {col: encoder.categories_[i] for i, col in enumerate(cat_columns)}
# Manual creation of feature names
feature_names = []
for i, col in enumerate(cat_columns):
    for category in encoder.categories_[i]:
        feature_names.append(f"{col}_{category}")

encoded_df = pd.DataFrame(encoded_df, columns=feature_names)

df.head()

,survived,pclass,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone,0,1,2,3,4
0,0,3,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False,0.0,1.0,0.0,1.0,0.0
1,1,1,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False,1.0,0.0,0.0,0.0,1.0
2,1,3,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True,1.0,0.0,0.0,0.0,1.0
3,1,1,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False,1.0,0.0,0.0,0.0,1.0
4,0,3,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True,0.0,1.0,0.0,1.0,0.0